//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("REMISModel", "FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(REMISModel.tblFTPTransaction), "tblFTPFile", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(REMISModel.tblFTPFile), true)]

#endregion

namespace REMISModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class REMISEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new REMISEntities object using the connection string found in the 'REMISEntities' section of the application configuration file.
        /// </summary>
        public REMISEntities() : base("name=REMISEntities", "REMISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new REMISEntities object.
        /// </summary>
        public REMISEntities(string connectionString) : base(connectionString, "REMISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new REMISEntities object.
        /// </summary>
        public REMISEntities(EntityConnection connection) : base(connection, "REMISEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCarrier> tblCarriers
        {
            get
            {
                if ((_tblCarriers == null))
                {
                    _tblCarriers = base.CreateObjectSet<tblCarrier>("tblCarriers");
                }
                return _tblCarriers;
            }
        }
        private ObjectSet<tblCarrier> _tblCarriers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblGTPIssue> tblGTPIssues
        {
            get
            {
                if ((_tblGTPIssues == null))
                {
                    _tblGTPIssues = base.CreateObjectSet<tblGTPIssue>("tblGTPIssues");
                }
                return _tblGTPIssues;
            }
        }
        private ObjectSet<tblGTPIssue> _tblGTPIssues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMarket> tblMarkets
        {
            get
            {
                if ((_tblMarkets == null))
                {
                    _tblMarkets = base.CreateObjectSet<tblMarket>("tblMarkets");
                }
                return _tblMarkets;
            }
        }
        private ObjectSet<tblMarket> _tblMarkets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblStatusInfo> tblStatusInfoes
        {
            get
            {
                if ((_tblStatusInfoes == null))
                {
                    _tblStatusInfoes = base.CreateObjectSet<tblStatusInfo>("tblStatusInfoes");
                }
                return _tblStatusInfoes;
            }
        }
        private ObjectSet<tblStatusInfo> _tblStatusInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<View_AllFiles> View_AllFiles
        {
            get
            {
                if ((_View_AllFiles == null))
                {
                    _View_AllFiles = base.CreateObjectSet<View_AllFiles>("View_AllFiles");
                }
                return _View_AllFiles;
            }
        }
        private ObjectSet<View_AllFiles> _View_AllFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFTPFile> tblFTPFiles
        {
            get
            {
                if ((_tblFTPFiles == null))
                {
                    _tblFTPFiles = base.CreateObjectSet<tblFTPFile>("tblFTPFiles");
                }
                return _tblFTPFiles;
            }
        }
        private ObjectSet<tblFTPFile> _tblFTPFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFTPTransaction> tblFTPTransactions
        {
            get
            {
                if ((_tblFTPTransactions == null))
                {
                    _tblFTPTransactions = base.CreateObjectSet<tblFTPTransaction>("tblFTPTransactions");
                }
                return _tblFTPTransactions;
            }
        }
        private ObjectSet<tblFTPTransaction> _tblFTPTransactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCarriers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCarriers(tblCarrier tblCarrier)
        {
            base.AddObject("tblCarriers", tblCarrier);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblGTPIssues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblGTPIssues(tblGTPIssue tblGTPIssue)
        {
            base.AddObject("tblGTPIssues", tblGTPIssue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMarkets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMarkets(tblMarket tblMarket)
        {
            base.AddObject("tblMarkets", tblMarket);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStatusInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStatusInfoes(tblStatusInfo tblStatusInfo)
        {
            base.AddObject("tblStatusInfoes", tblStatusInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the View_AllFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToView_AllFiles(View_AllFiles view_AllFiles)
        {
            base.AddObject("View_AllFiles", view_AllFiles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFTPFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFTPFiles(tblFTPFile tblFTPFile)
        {
            base.AddObject("tblFTPFiles", tblFTPFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFTPTransactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFTPTransactions(tblFTPTransaction tblFTPTransaction)
        {
            base.AddObject("tblFTPTransactions", tblFTPTransaction);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblCarrier")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCarrier : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCarrier object.
        /// </summary>
        /// <param name="id_carrier">Initial value of the id_carrier property.</param>
        public static tblCarrier CreatetblCarrier(global::System.Int32 id_carrier)
        {
            tblCarrier tblCarrier = new tblCarrier();
            tblCarrier.id_carrier = id_carrier;
            return tblCarrier;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_carrier
        {
            get
            {
                return _id_carrier;
            }
            set
            {
                if (_id_carrier != value)
                {
                    Onid_carrierChanging(value);
                    ReportPropertyChanging("id_carrier");
                    _id_carrier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_carrier");
                    Onid_carrierChanged();
                }
            }
        }
        private global::System.Int32 _id_carrier;
        partial void Onid_carrierChanging(global::System.Int32 value);
        partial void Onid_carrierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_carrier
        {
            get
            {
                return _name_carrier;
            }
            set
            {
                Onname_carrierChanging(value);
                ReportPropertyChanging("name_carrier");
                _name_carrier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_carrier");
                Onname_carrierChanged();
            }
        }
        private global::System.String _name_carrier;
        partial void Onname_carrierChanging(global::System.String value);
        partial void Onname_carrierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isCarrier
        {
            get
            {
                return _isCarrier;
            }
            set
            {
                OnisCarrierChanging(value);
                ReportPropertyChanging("isCarrier");
                _isCarrier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isCarrier");
                OnisCarrierChanged();
            }
        }
        private Nullable<global::System.Boolean> _isCarrier;
        partial void OnisCarrierChanging(Nullable<global::System.Boolean> value);
        partial void OnisCarrierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VoiceTech
        {
            get
            {
                return _VoiceTech;
            }
            set
            {
                OnVoiceTechChanging(value);
                ReportPropertyChanging("VoiceTech");
                _VoiceTech = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VoiceTech");
                OnVoiceTechChanged();
            }
        }
        private global::System.String _VoiceTech;
        partial void OnVoiceTechChanging(global::System.String value);
        partial void OnVoiceTechChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataTech
        {
            get
            {
                return _DataTech;
            }
            set
            {
                OnDataTechChanging(value);
                ReportPropertyChanging("DataTech");
                _DataTech = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataTech");
                OnDataTechChanged();
            }
        }
        private global::System.String _DataTech;
        partial void OnDataTechChanging(global::System.String value);
        partial void OnDataTechChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DataTechList
        {
            get
            {
                return _DataTechList;
            }
            set
            {
                OnDataTechListChanging(value);
                ReportPropertyChanging("DataTechList");
                _DataTechList = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DataTechList");
                OnDataTechListChanged();
            }
        }
        private global::System.String _DataTechList;
        partial void OnDataTechListChanging(global::System.String value);
        partial void OnDataTechListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColorCode
        {
            get
            {
                return _ColorCode;
            }
            set
            {
                OnColorCodeChanging(value);
                ReportPropertyChanging("ColorCode");
                _ColorCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ColorCode");
                OnColorCodeChanged();
            }
        }
        private global::System.String _ColorCode;
        partial void OnColorCodeChanging(global::System.String value);
        partial void OnColorCodeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblFTPFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFTPFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFTPFile object.
        /// </summary>
        /// <param name="id_server_file">Initial value of the id_server_file property.</param>
        public static tblFTPFile CreatetblFTPFile(global::System.Int32 id_server_file)
        {
            tblFTPFile tblFTPFile = new tblFTPFile();
            tblFTPFile.id_server_file = id_server_file;
            return tblFTPFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_server_file
        {
            get
            {
                return _id_server_file;
            }
            set
            {
                if (_id_server_file != value)
                {
                    Onid_server_fileChanging(value);
                    ReportPropertyChanging("id_server_file");
                    _id_server_file = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_server_file");
                    Onid_server_fileChanged();
                }
            }
        }
        private global::System.Int32 _id_server_file;
        partial void Onid_server_fileChanging(global::System.Int32 value);
        partial void Onid_server_fileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_server_transaction
        {
            get
            {
                return _id_server_transaction;
            }
            set
            {
                Onid_server_transactionChanging(value);
                ReportPropertyChanging("id_server_transaction");
                _id_server_transaction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_server_transaction");
                Onid_server_transactionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_server_transaction;
        partial void Onid_server_transactionChanging(Nullable<global::System.Int32> value);
        partial void Onid_server_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_client_transaction
        {
            get
            {
                return _id_client_transaction;
            }
            set
            {
                Onid_client_transactionChanging(value);
                ReportPropertyChanging("id_client_transaction");
                _id_client_transaction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_client_transaction");
                Onid_client_transactionChanged();
            }
        }
        private Nullable<global::System.Int32> _id_client_transaction;
        partial void Onid_client_transactionChanging(Nullable<global::System.Int32> value);
        partial void Onid_client_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String file_name
        {
            get
            {
                return _file_name;
            }
            set
            {
                Onfile_nameChanging(value);
                ReportPropertyChanging("file_name");
                _file_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("file_name");
                Onfile_nameChanged();
            }
        }
        private global::System.String _file_name;
        partial void Onfile_nameChanging(global::System.String value);
        partial void Onfile_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_created
        {
            get
            {
                return _date_created;
            }
            set
            {
                Ondate_createdChanging(value);
                ReportPropertyChanging("date_created");
                _date_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_created");
                Ondate_createdChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_created;
        partial void Ondate_createdChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_finished
        {
            get
            {
                return _date_finished;
            }
            set
            {
                Ondate_finishedChanging(value);
                ReportPropertyChanging("date_finished");
                _date_finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_finished");
                Ondate_finishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_finished;
        partial void Ondate_finishedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_finishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_finished
        {
            get
            {
                return _is_finished;
            }
            set
            {
                Onis_finishedChanging(value);
                ReportPropertyChanging("is_finished");
                _is_finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_finished");
                Onis_finishedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_finished;
        partial void Onis_finishedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_finishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> file_status
        {
            get
            {
                return _file_status;
            }
            set
            {
                Onfile_statusChanging(value);
                ReportPropertyChanging("file_status");
                _file_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("file_status");
                Onfile_statusChanged();
            }
        }
        private Nullable<global::System.Int32> _file_status;
        partial void Onfile_statusChanging(Nullable<global::System.Int32> value);
        partial void Onfile_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time_moved_NQWeb
        {
            get
            {
                return _time_moved_NQWeb;
            }
            set
            {
                Ontime_moved_NQWebChanging(value);
                ReportPropertyChanging("time_moved_NQWeb");
                _time_moved_NQWeb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_moved_NQWeb");
                Ontime_moved_NQWebChanged();
            }
        }
        private Nullable<global::System.DateTime> _time_moved_NQWeb;
        partial void Ontime_moved_NQWebChanging(Nullable<global::System.DateTime> value);
        partial void Ontime_moved_NQWebChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("REMISModel", "FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction")]
        public tblFTPTransaction tblFTPTransaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblFTPTransaction>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblFTPTransaction>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblFTPTransaction> tblFTPTransactionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblFTPTransaction>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblFTPTransaction>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPTransaction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblFTPTransaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFTPTransaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFTPTransaction object.
        /// </summary>
        /// <param name="id_server_transaction">Initial value of the id_server_transaction property.</param>
        /// <param name="id_client_transaction">Initial value of the id_client_transaction property.</param>
        public static tblFTPTransaction CreatetblFTPTransaction(global::System.Int32 id_server_transaction, global::System.Int32 id_client_transaction)
        {
            tblFTPTransaction tblFTPTransaction = new tblFTPTransaction();
            tblFTPTransaction.id_server_transaction = id_server_transaction;
            tblFTPTransaction.id_client_transaction = id_client_transaction;
            return tblFTPTransaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_server_transaction
        {
            get
            {
                return _id_server_transaction;
            }
            set
            {
                if (_id_server_transaction != value)
                {
                    Onid_server_transactionChanging(value);
                    ReportPropertyChanging("id_server_transaction");
                    _id_server_transaction = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_server_transaction");
                    Onid_server_transactionChanged();
                }
            }
        }
        private global::System.Int32 _id_server_transaction;
        partial void Onid_server_transactionChanging(global::System.Int32 value);
        partial void Onid_server_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_client_transaction
        {
            get
            {
                return _id_client_transaction;
            }
            set
            {
                Onid_client_transactionChanging(value);
                ReportPropertyChanging("id_client_transaction");
                _id_client_transaction = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_client_transaction");
                Onid_client_transactionChanged();
            }
        }
        private global::System.Int32 _id_client_transaction;
        partial void Onid_client_transactionChanging(global::System.Int32 value);
        partial void Onid_client_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> transaction_type
        {
            get
            {
                return _transaction_type;
            }
            set
            {
                Ontransaction_typeChanging(value);
                ReportPropertyChanging("transaction_type");
                _transaction_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transaction_type");
                Ontransaction_typeChanged();
            }
        }
        private Nullable<global::System.Boolean> _transaction_type;
        partial void Ontransaction_typeChanging(Nullable<global::System.Boolean> value);
        partial void Ontransaction_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_started
        {
            get
            {
                return _date_started;
            }
            set
            {
                Ondate_startedChanging(value);
                ReportPropertyChanging("date_started");
                _date_started = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_started");
                Ondate_startedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_started;
        partial void Ondate_startedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_startedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_end
        {
            get
            {
                return _date_end;
            }
            set
            {
                Ondate_endChanging(value);
                ReportPropertyChanging("date_end");
                _date_end = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_end");
                Ondate_endChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_end;
        partial void Ondate_endChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_endChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isCompleted
        {
            get
            {
                return _isCompleted;
            }
            set
            {
                OnisCompletedChanging(value);
                ReportPropertyChanging("isCompleted");
                _isCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isCompleted");
                OnisCompletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _isCompleted;
        partial void OnisCompletedChanging(Nullable<global::System.Boolean> value);
        partial void OnisCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> number_of_run
        {
            get
            {
                return _number_of_run;
            }
            set
            {
                Onnumber_of_runChanging(value);
                ReportPropertyChanging("number_of_run");
                _number_of_run = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number_of_run");
                Onnumber_of_runChanged();
            }
        }
        private Nullable<global::System.Int16> _number_of_run;
        partial void Onnumber_of_runChanging(Nullable<global::System.Int16> value);
        partial void Onnumber_of_runChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> number_of_app_fail
        {
            get
            {
                return _number_of_app_fail;
            }
            set
            {
                Onnumber_of_app_failChanging(value);
                ReportPropertyChanging("number_of_app_fail");
                _number_of_app_fail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number_of_app_fail");
                Onnumber_of_app_failChanged();
            }
        }
        private Nullable<global::System.Int16> _number_of_app_fail;
        partial void Onnumber_of_app_failChanging(Nullable<global::System.Int16> value);
        partial void Onnumber_of_app_failChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_market
        {
            get
            {
                return _id_market;
            }
            set
            {
                Onid_marketChanging(value);
                ReportPropertyChanging("id_market");
                _id_market = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_market");
                Onid_marketChanged();
            }
        }
        private Nullable<global::System.Int32> _id_market;
        partial void Onid_marketChanging(Nullable<global::System.Int32> value);
        partial void Onid_marketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_url
        {
            get
            {
                return _ftp_url;
            }
            set
            {
                Onftp_urlChanging(value);
                ReportPropertyChanging("ftp_url");
                _ftp_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_url");
                Onftp_urlChanged();
            }
        }
        private global::System.String _ftp_url;
        partial void Onftp_urlChanging(global::System.String value);
        partial void Onftp_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_address
        {
            get
            {
                return _ip_address;
            }
            set
            {
                Onip_addressChanging(value);
                ReportPropertyChanging("ip_address");
                _ip_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_address");
                Onip_addressChanged();
            }
        }
        private global::System.String _ip_address;
        partial void Onip_addressChanging(global::System.String value);
        partial void Onip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String host_name
        {
            get
            {
                return _host_name;
            }
            set
            {
                Onhost_nameChanging(value);
                ReportPropertyChanging("host_name");
                _host_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("host_name");
                Onhost_nameChanged();
            }
        }
        private global::System.String _host_name;
        partial void Onhost_nameChanging(global::System.String value);
        partial void Onhost_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_name
        {
            get
            {
                return _market_name;
            }
            set
            {
                Onmarket_nameChanging(value);
                ReportPropertyChanging("market_name");
                _market_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_name");
                Onmarket_nameChanged();
            }
        }
        private global::System.String _market_name;
        partial void Onmarket_nameChanging(global::System.String value);
        partial void Onmarket_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> transaction_status
        {
            get
            {
                return _transaction_status;
            }
            set
            {
                Ontransaction_statusChanging(value);
                ReportPropertyChanging("transaction_status");
                _transaction_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transaction_status");
                Ontransaction_statusChanged();
            }
        }
        private Nullable<global::System.Int16> _transaction_status;
        partial void Ontransaction_statusChanging(Nullable<global::System.Int16> value);
        partial void Ontransaction_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time_moveFiles
        {
            get
            {
                return _time_moveFiles;
            }
            set
            {
                Ontime_moveFilesChanging(value);
                ReportPropertyChanging("time_moveFiles");
                _time_moveFiles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_moveFiles");
                Ontime_moveFilesChanged();
            }
        }
        private Nullable<global::System.DateTime> _time_moveFiles;
        partial void Ontime_moveFilesChanging(Nullable<global::System.DateTime> value);
        partial void Ontime_moveFilesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> total_file_uploaded
        {
            get
            {
                return _total_file_uploaded;
            }
            set
            {
                Ontotal_file_uploadedChanging(value);
                ReportPropertyChanging("total_file_uploaded");
                _total_file_uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_file_uploaded");
                Ontotal_file_uploadedChanged();
            }
        }
        private Nullable<global::System.Int32> _total_file_uploaded;
        partial void Ontotal_file_uploadedChanging(Nullable<global::System.Int32> value);
        partial void Ontotal_file_uploadedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("REMISModel", "FK_tblFTPFile_tblFTPTransaction", "tblFTPFile")]
        public EntityCollection<tblFTPFile> tblFTPFiles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblFTPFile>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblFTPFile>("REMISModel.FK_tblFTPFile_tblFTPTransaction", "tblFTPFile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblGTPIssue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblGTPIssue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblGTPIssue object.
        /// </summary>
        /// <param name="id_issue">Initial value of the id_issue property.</param>
        public static tblGTPIssue CreatetblGTPIssue(global::System.Int32 id_issue)
        {
            tblGTPIssue tblGTPIssue = new tblGTPIssue();
            tblGTPIssue.id_issue = id_issue;
            return tblGTPIssue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_issue
        {
            get
            {
                return _id_issue;
            }
            set
            {
                if (_id_issue != value)
                {
                    Onid_issueChanging(value);
                    ReportPropertyChanging("id_issue");
                    _id_issue = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_issue");
                    Onid_issueChanged();
                }
            }
        }
        private global::System.Int32 _id_issue;
        partial void Onid_issueChanging(global::System.Int32 value);
        partial void Onid_issueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String issue_title
        {
            get
            {
                return _issue_title;
            }
            set
            {
                Onissue_titleChanging(value);
                ReportPropertyChanging("issue_title");
                _issue_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("issue_title");
                Onissue_titleChanged();
            }
        }
        private global::System.String _issue_title;
        partial void Onissue_titleChanging(global::System.String value);
        partial void Onissue_titleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String issue_detail
        {
            get
            {
                return _issue_detail;
            }
            set
            {
                Onissue_detailChanging(value);
                ReportPropertyChanging("issue_detail");
                _issue_detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("issue_detail");
                Onissue_detailChanged();
            }
        }
        private global::System.String _issue_detail;
        partial void Onissue_detailChanging(global::System.String value);
        partial void Onissue_detailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String issue_file_upload
        {
            get
            {
                return _issue_file_upload;
            }
            set
            {
                Onissue_file_uploadChanging(value);
                ReportPropertyChanging("issue_file_upload");
                _issue_file_upload = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("issue_file_upload");
                Onissue_file_uploadChanged();
            }
        }
        private global::System.String _issue_file_upload;
        partial void Onissue_file_uploadChanging(global::System.String value);
        partial void Onissue_file_uploadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_created
        {
            get
            {
                return _date_created;
            }
            set
            {
                Ondate_createdChanging(value);
                ReportPropertyChanging("date_created");
                _date_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_created");
                Ondate_createdChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_created;
        partial void Ondate_createdChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String team_name
        {
            get
            {
                return _team_name;
            }
            set
            {
                Onteam_nameChanging(value);
                ReportPropertyChanging("team_name");
                _team_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("team_name");
                Onteam_nameChanged();
            }
        }
        private global::System.String _team_name;
        partial void Onteam_nameChanging(global::System.String value);
        partial void Onteam_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_name
        {
            get
            {
                return _market_name;
            }
            set
            {
                Onmarket_nameChanging(value);
                ReportPropertyChanging("market_name");
                _market_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_name");
                Onmarket_nameChanged();
            }
        }
        private global::System.String _market_name;
        partial void Onmarket_nameChanging(global::System.String value);
        partial void Onmarket_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String campaign
        {
            get
            {
                return _campaign;
            }
            set
            {
                OncampaignChanging(value);
                ReportPropertyChanging("campaign");
                _campaign = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("campaign");
                OncampaignChanged();
            }
        }
        private global::System.String _campaign;
        partial void OncampaignChanging(global::System.String value);
        partial void OncampaignChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblMarket")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMarket : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMarket object.
        /// </summary>
        /// <param name="id_market">Initial value of the id_market property.</param>
        public static tblMarket CreatetblMarket(global::System.Int32 id_market)
        {
            tblMarket tblMarket = new tblMarket();
            tblMarket.id_market = id_market;
            return tblMarket;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_market
        {
            get
            {
                return _id_market;
            }
            set
            {
                if (_id_market != value)
                {
                    Onid_marketChanging(value);
                    ReportPropertyChanging("id_market");
                    _id_market = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_market");
                    Onid_marketChanged();
                }
            }
        }
        private global::System.Int32 _id_market;
        partial void Onid_marketChanging(global::System.Int32 value);
        partial void Onid_marketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_market
        {
            get
            {
                return _name_market;
            }
            set
            {
                Onname_marketChanging(value);
                ReportPropertyChanging("name_market");
                _name_market = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_market");
                Onname_marketChanged();
            }
        }
        private global::System.String _name_market;
        partial void Onname_marketChanging(global::System.String value);
        partial void Onname_marketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String population
        {
            get
            {
                return _population;
            }
            set
            {
                OnpopulationChanging(value);
                ReportPropertyChanging("population");
                _population = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("population");
                OnpopulationChanged();
            }
        }
        private global::System.String _population;
        partial void OnpopulationChanging(global::System.String value);
        partial void OnpopulationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_type
        {
            get
            {
                return _market_type;
            }
            set
            {
                Onmarket_typeChanging(value);
                ReportPropertyChanging("market_type");
                _market_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_type");
                Onmarket_typeChanged();
            }
        }
        private global::System.String _market_type;
        partial void Onmarket_typeChanging(global::System.String value);
        partial void Onmarket_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_region
        {
            get
            {
                return _market_region;
            }
            set
            {
                Onmarket_regionChanging(value);
                ReportPropertyChanging("market_region");
                _market_region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_region");
                Onmarket_regionChanged();
            }
        }
        private global::System.String _market_region;
        partial void Onmarket_regionChanging(global::System.String value);
        partial void Onmarket_regionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_ed
        {
            get
            {
                return _market_ed;
            }
            set
            {
                Onmarket_edChanging(value);
                ReportPropertyChanging("market_ed");
                _market_ed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_ed");
                Onmarket_edChanged();
            }
        }
        private global::System.String _market_ed;
        partial void Onmarket_edChanging(global::System.String value);
        partial void Onmarket_edChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sub_market
        {
            get
            {
                return _sub_market;
            }
            set
            {
                Onsub_marketChanging(value);
                ReportPropertyChanging("sub_market");
                _sub_market = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sub_market");
                Onsub_marketChanged();
            }
        }
        private global::System.String _sub_market;
        partial void Onsub_marketChanging(global::System.String value);
        partial void Onsub_marketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> market_status
        {
            get
            {
                return _market_status;
            }
            set
            {
                Onmarket_statusChanging(value);
                ReportPropertyChanging("market_status");
                _market_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("market_status");
                Onmarket_statusChanged();
            }
        }
        private Nullable<global::System.Int16> _market_status;
        partial void Onmarket_statusChanging(Nullable<global::System.Int16> value);
        partial void Onmarket_statusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="tblStatusInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblStatusInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblStatusInfo object.
        /// </summary>
        /// <param name="id_status">Initial value of the id_status property.</param>
        public static tblStatusInfo CreatetblStatusInfo(global::System.Int32 id_status)
        {
            tblStatusInfo tblStatusInfo = new tblStatusInfo();
            tblStatusInfo.id_status = id_status;
            return tblStatusInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_status
        {
            get
            {
                return _id_status;
            }
            set
            {
                if (_id_status != value)
                {
                    Onid_statusChanging(value);
                    ReportPropertyChanging("id_status");
                    _id_status = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_status");
                    Onid_statusChanged();
                }
            }
        }
        private global::System.Int32 _id_status;
        partial void Onid_statusChanging(global::System.Int32 value);
        partial void Onid_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status_code
        {
            get
            {
                return _status_code;
            }
            set
            {
                Onstatus_codeChanging(value);
                ReportPropertyChanging("status_code");
                _status_code = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status_code");
                Onstatus_codeChanged();
            }
        }
        private Nullable<global::System.Int32> _status_code;
        partial void Onstatus_codeChanging(Nullable<global::System.Int32> value);
        partial void Onstatus_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status_name
        {
            get
            {
                return _status_name;
            }
            set
            {
                Onstatus_nameChanging(value);
                ReportPropertyChanging("status_name");
                _status_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status_name");
                Onstatus_nameChanged();
            }
        }
        private global::System.String _status_name;
        partial void Onstatus_nameChanging(global::System.String value);
        partial void Onstatus_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="REMISModel", Name="View_AllFiles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class View_AllFiles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new View_AllFiles object.
        /// </summary>
        /// <param name="id_server_transaction">Initial value of the id_server_transaction property.</param>
        /// <param name="id_client_transaction">Initial value of the id_client_transaction property.</param>
        /// <param name="id_server_file">Initial value of the id_server_file property.</param>
        public static View_AllFiles CreateView_AllFiles(global::System.Int32 id_server_transaction, global::System.Int32 id_client_transaction, global::System.Int32 id_server_file)
        {
            View_AllFiles view_AllFiles = new View_AllFiles();
            view_AllFiles.id_server_transaction = id_server_transaction;
            view_AllFiles.id_client_transaction = id_client_transaction;
            view_AllFiles.id_server_file = id_server_file;
            return view_AllFiles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_server_transaction
        {
            get
            {
                return _id_server_transaction;
            }
            set
            {
                if (_id_server_transaction != value)
                {
                    Onid_server_transactionChanging(value);
                    ReportPropertyChanging("id_server_transaction");
                    _id_server_transaction = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_server_transaction");
                    Onid_server_transactionChanged();
                }
            }
        }
        private global::System.Int32 _id_server_transaction;
        partial void Onid_server_transactionChanging(global::System.Int32 value);
        partial void Onid_server_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_client_transaction
        {
            get
            {
                return _id_client_transaction;
            }
            set
            {
                if (_id_client_transaction != value)
                {
                    Onid_client_transactionChanging(value);
                    ReportPropertyChanging("id_client_transaction");
                    _id_client_transaction = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_client_transaction");
                    Onid_client_transactionChanged();
                }
            }
        }
        private global::System.Int32 _id_client_transaction;
        partial void Onid_client_transactionChanging(global::System.Int32 value);
        partial void Onid_client_transactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> transaction_type
        {
            get
            {
                return _transaction_type;
            }
            set
            {
                Ontransaction_typeChanging(value);
                ReportPropertyChanging("transaction_type");
                _transaction_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transaction_type");
                Ontransaction_typeChanged();
            }
        }
        private Nullable<global::System.Boolean> _transaction_type;
        partial void Ontransaction_typeChanging(Nullable<global::System.Boolean> value);
        partial void Ontransaction_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_started
        {
            get
            {
                return _date_started;
            }
            set
            {
                Ondate_startedChanging(value);
                ReportPropertyChanging("date_started");
                _date_started = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_started");
                Ondate_startedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_started;
        partial void Ondate_startedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_startedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_end
        {
            get
            {
                return _date_end;
            }
            set
            {
                Ondate_endChanging(value);
                ReportPropertyChanging("date_end");
                _date_end = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_end");
                Ondate_endChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_end;
        partial void Ondate_endChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_endChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isCompleted
        {
            get
            {
                return _isCompleted;
            }
            set
            {
                OnisCompletedChanging(value);
                ReportPropertyChanging("isCompleted");
                _isCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isCompleted");
                OnisCompletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _isCompleted;
        partial void OnisCompletedChanging(Nullable<global::System.Boolean> value);
        partial void OnisCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> number_of_run
        {
            get
            {
                return _number_of_run;
            }
            set
            {
                Onnumber_of_runChanging(value);
                ReportPropertyChanging("number_of_run");
                _number_of_run = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number_of_run");
                Onnumber_of_runChanged();
            }
        }
        private Nullable<global::System.Int16> _number_of_run;
        partial void Onnumber_of_runChanging(Nullable<global::System.Int16> value);
        partial void Onnumber_of_runChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_market
        {
            get
            {
                return _id_market;
            }
            set
            {
                Onid_marketChanging(value);
                ReportPropertyChanging("id_market");
                _id_market = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_market");
                Onid_marketChanged();
            }
        }
        private Nullable<global::System.Int32> _id_market;
        partial void Onid_marketChanging(Nullable<global::System.Int32> value);
        partial void Onid_marketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ftp_url
        {
            get
            {
                return _ftp_url;
            }
            set
            {
                Onftp_urlChanging(value);
                ReportPropertyChanging("ftp_url");
                _ftp_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ftp_url");
                Onftp_urlChanged();
            }
        }
        private global::System.String _ftp_url;
        partial void Onftp_urlChanging(global::System.String value);
        partial void Onftp_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ip_address
        {
            get
            {
                return _ip_address;
            }
            set
            {
                Onip_addressChanging(value);
                ReportPropertyChanging("ip_address");
                _ip_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ip_address");
                Onip_addressChanged();
            }
        }
        private global::System.String _ip_address;
        partial void Onip_addressChanging(global::System.String value);
        partial void Onip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String host_name
        {
            get
            {
                return _host_name;
            }
            set
            {
                Onhost_nameChanging(value);
                ReportPropertyChanging("host_name");
                _host_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("host_name");
                Onhost_nameChanged();
            }
        }
        private global::System.String _host_name;
        partial void Onhost_nameChanging(global::System.String value);
        partial void Onhost_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market_name
        {
            get
            {
                return _market_name;
            }
            set
            {
                Onmarket_nameChanging(value);
                ReportPropertyChanging("market_name");
                _market_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market_name");
                Onmarket_nameChanged();
            }
        }
        private global::System.String _market_name;
        partial void Onmarket_nameChanging(global::System.String value);
        partial void Onmarket_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> transaction_status
        {
            get
            {
                return _transaction_status;
            }
            set
            {
                Ontransaction_statusChanging(value);
                ReportPropertyChanging("transaction_status");
                _transaction_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transaction_status");
                Ontransaction_statusChanged();
            }
        }
        private Nullable<global::System.Int16> _transaction_status;
        partial void Ontransaction_statusChanging(Nullable<global::System.Int16> value);
        partial void Ontransaction_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time_moveFiles
        {
            get
            {
                return _time_moveFiles;
            }
            set
            {
                Ontime_moveFilesChanging(value);
                ReportPropertyChanging("time_moveFiles");
                _time_moveFiles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_moveFiles");
                Ontime_moveFilesChanged();
            }
        }
        private Nullable<global::System.DateTime> _time_moveFiles;
        partial void Ontime_moveFilesChanging(Nullable<global::System.DateTime> value);
        partial void Ontime_moveFilesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DBName
        {
            get
            {
                return _DBName;
            }
            set
            {
                OnDBNameChanging(value);
                ReportPropertyChanging("DBName");
                _DBName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DBName");
                OnDBNameChanged();
            }
        }
        private global::System.String _DBName;
        partial void OnDBNameChanging(global::System.String value);
        partial void OnDBNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> total_file_uploaded
        {
            get
            {
                return _total_file_uploaded;
            }
            set
            {
                Ontotal_file_uploadedChanging(value);
                ReportPropertyChanging("total_file_uploaded");
                _total_file_uploaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_file_uploaded");
                Ontotal_file_uploadedChanged();
            }
        }
        private Nullable<global::System.Int32> _total_file_uploaded;
        partial void Ontotal_file_uploadedChanging(Nullable<global::System.Int32> value);
        partial void Ontotal_file_uploadedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_server_file
        {
            get
            {
                return _id_server_file;
            }
            set
            {
                if (_id_server_file != value)
                {
                    Onid_server_fileChanging(value);
                    ReportPropertyChanging("id_server_file");
                    _id_server_file = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_server_file");
                    Onid_server_fileChanged();
                }
            }
        }
        private global::System.Int32 _id_server_file;
        partial void Onid_server_fileChanging(global::System.Int32 value);
        partial void Onid_server_fileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String file_name
        {
            get
            {
                return _file_name;
            }
            set
            {
                Onfile_nameChanging(value);
                ReportPropertyChanging("file_name");
                _file_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("file_name");
                Onfile_nameChanged();
            }
        }
        private global::System.String _file_name;
        partial void Onfile_nameChanging(global::System.String value);
        partial void Onfile_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_created
        {
            get
            {
                return _date_created;
            }
            set
            {
                Ondate_createdChanging(value);
                ReportPropertyChanging("date_created");
                _date_created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_created");
                Ondate_createdChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_created;
        partial void Ondate_createdChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_createdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_finished
        {
            get
            {
                return _date_finished;
            }
            set
            {
                Ondate_finishedChanging(value);
                ReportPropertyChanging("date_finished");
                _date_finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_finished");
                Ondate_finishedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_finished;
        partial void Ondate_finishedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_finishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_finished
        {
            get
            {
                return _is_finished;
            }
            set
            {
                Onis_finishedChanging(value);
                ReportPropertyChanging("is_finished");
                _is_finished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_finished");
                Onis_finishedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_finished;
        partial void Onis_finishedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_finishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> file_status
        {
            get
            {
                return _file_status;
            }
            set
            {
                Onfile_statusChanging(value);
                ReportPropertyChanging("file_status");
                _file_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("file_status");
                Onfile_statusChanged();
            }
        }
        private Nullable<global::System.Int16> _file_status;
        partial void Onfile_statusChanging(Nullable<global::System.Int16> value);
        partial void Onfile_statusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time_moved_NQWeb
        {
            get
            {
                return _time_moved_NQWeb;
            }
            set
            {
                Ontime_moved_NQWebChanging(value);
                ReportPropertyChanging("time_moved_NQWeb");
                _time_moved_NQWeb = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_moved_NQWeb");
                Ontime_moved_NQWebChanged();
            }
        }
        private Nullable<global::System.DateTime> _time_moved_NQWeb;
        partial void Ontime_moved_NQWebChanging(Nullable<global::System.DateTime> value);
        partial void Ontime_moved_NQWebChanged();

        #endregion

    
    }

    #endregion

    
}
